### ISSUE TITLE
NullPointerException while launching a RuntimeConfiguration

### ISSUE THREAD

**Issue by cecchisandrone** [tsvetan-stoyanov/launchpi#10] opened 2015-01-19 18:18 UTC
Hello,

I've got a NullPointerException while launching a RuntimeConfiguration. This is the stacktrace:
````
java.lang.NullPointerException
	at org.launchpi.launcher.ProjectSynchronizer.createClasspathArchive(ProjectSynchronizer.java:72)
	at org.launchpi.launcher.ProjectSynchronizer.synchronize(ProjectSynchronizer.java:52)
	at org.launchpi.launcher.RemoteProcessFactory.createRemoteProcess(RemoteProcessFactory.java:67)
	at org.launchpi.launcher.RPILaunchConfigurationDelegate.launch(RPILaunchConfigurationDelegate.java:18)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:858)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:707)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1018)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)
````
I would like to solve it by debugging the plugin but I didn't succeed. Can you please explain me the steps to run the plugin in debug?

Regards

**Comment by cecchisandrone** [comment] 2015-01-19 20:09
I've discovered that the problem is due to Maven setting "Resolve dependencies from workspace projects" enabled

**Comment by tsvetan-stoyanov** [comment] 2015-01-19 20:10
Hi Alessandro,

After cloning the project repository import the projects as "Existing Maven Projects". After the import you should be able to launch a new Eclipse Application including the just imported plugin. Let me know if this works for you.

In regards to the bug - it seems that your project has a classpath entry different than IClasspathEntry.CPE_SOURCE and IClasspathEntry.CPE_LIBRARY and the handling of such entries is not correct. Can you please share some details what is the classpath of the project?

10x
Tsvetan

**Comment by tsvetan-stoyanov** [comment] 2015-12-14 22:25
Duplicate of #12.
Fixed

**Closed by tsvetan-stoyanov** 2015-12-14 22:25 UTC
